fix typo in events.mdx
teamkeel/docs pull request #126
Opened 2024-04-07 10:05 UTC by seeekr

not sure if I'm making the correct suggestion, but the original code cannot possibly work because there is no `member` variable.

2024-04-07 10:06 UTC, seeekr commented
oh shoot, it should probably be `event.target.data.emailVerified` instead?

2024-04-08 05:49 UTC, davenewza commented
> oh shoot, it should probably be `event.target.data.emailVerified` instead?

@seeekr well spotted, and yes, you're correct that it's `event.target.data.emailVerified`

2024-04-08 05:50 UTC, davenewza commented on pages/events.mdx
> +      if (!event.data.emailVerified) {
```suggestion
      if (!event.target.data.emailVerified) {
```

2024-04-08 05:51 UTC, davenewza requested changes
Please do pop a fix in as per your suggestion

2024-07-29 05:12 UTC, davenewza approved these changes

2024-07-29 05:12 UTC, merged